### ISSUE TITLE
Cannot execute `token.py` with jose imports

### ISSUE THREAD

**Issue by vmarkovtsev** [mpdavis/python-jose#172]
### Summary

`import jose` in a file named `token.py` crashes.

### Reproduction

Save this line as `token.py`:

```python
from jose import jwt
```

Then

```
python3 token.py
```

You should see

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jose/utils.py", line 17, in <module>
    from Crypto.Util.number import long_to_bytes
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "token.py", line 1, in <module>
    from jose import jwt
  File "/usr/local/lib/python3.7/dist-packages/jose/jwt.py", line 13, in <module>
    from jose import jws
  File "/usr/local/lib/python3.7/dist-packages/jose/jws.py", line 11, in <module>
    from jose import jwk
  File "/usr/local/lib/python3.7/dist-packages/jose/jwk.py", line 8, in <module>
    from jose.utils import base64url_decode, base64url_encode
  File "/usr/local/lib/python3.7/dist-packages/jose/utils.py", line 20, in <module>
    from cryptography.utils import int_to_bytes as _long_to_bytes
  File "/usr/lib/python3/dist-packages/cryptography/utils.py", line 9, in <module>
    import inspect
  File "/usr/lib/python3.7/inspect.py", line 40, in <module>
    import linecache
  File "/usr/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib/python3.7/tokenize.py", line 41, in <module>
    __all__ = token.__all__ + ["tokenize", "detect_encoding",
AttributeError: module 'token' has no attribute '__all__'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 62, in apport_excepthook
    import re, traceback
  File "/usr/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib/python3.7/tokenize.py", line 41, in <module>
    __all__ = token.__all__ + ["tokenize", "detect_encoding",
AttributeError: module 'token' has no attribute '__all__'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jose/utils.py", line 17, in <module>
    from Crypto.Util.number import long_to_bytes
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "token.py", line 1, in <module>
    from jose import jwt
  File "/usr/local/lib/python3.7/dist-packages/jose/jwt.py", line 13, in <module>
    from jose import jws
  File "/usr/local/lib/python3.7/dist-packages/jose/jws.py", line 11, in <module>
    from jose import jwk
  File "/usr/local/lib/python3.7/dist-packages/jose/jwk.py", line 8, in <module>
    from jose.utils import base64url_decode, base64url_encode
  File "/usr/local/lib/python3.7/dist-packages/jose/utils.py", line 20, in <module>
    from cryptography.utils import int_to_bytes as _long_to_bytes
  File "/usr/lib/python3/dist-packages/cryptography/utils.py", line 9, in <module>
    import inspect
  File "/usr/lib/python3.7/inspect.py", line 40, in <module>
    import linecache
  File "/usr/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib/python3.7/tokenize.py", line 41, in <module>
    __all__ = token.__all__ + ["tokenize", "detect_encoding",
AttributeError: module 'token' has no attribute '__all__'
```

I bet that the reason is that `jose` messes with `sys.path` somewhere so that `token.py` precedes the real `token` package and a nasty name collision occurs.

### System info

- Python 3.7.5 
- python-jose 3.1.0
- Ubuntu 19.10

**Comment by vmarkovtsev** [comment]
This is not an issue with `jose`. The same error appears with `import cryptography.utils`. Damn Ubuntu's Python is so broken. Sorry for the noise.
