### ISSUE TITLE
Import fails on Python 3.4 (and probably earlier versions of Python 3)

### ISSUE THREAD

**Issue by craigafinch** [mpdavis/python-jose#3]
Steps to reproduce:
1. Run a python 3.4 interpreter
2. import jose.jws
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/jose/jws.py", line 8, in <module>
    from jose.jwa import get_algorithm_object
  File "/usr/local/lib/python3.4/dist-packages/jose/jwa.py", line 97
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by mpdavis** [comment]
@craigafinch I hadn't originally supported python 3, but now is as good as ever. 

Version 0.5.0 and above should be python 3 compatible. 

Let me know if run into any problems.
